### ISSUE TITLE
Manual boxing in xboxcontroller

### ISSUE THREAD

**Issue by leijurv** [RoboticsTeam4904/standard#124]
`final float amount = new Float(intensity);` why???? this doesn't do anything

**Comment by c0d3rman** [comment]
That's just silly. This is a part of team 4624's XboxController library, and as the author writes at the top of the file:
```
I am not a good Java programmer.
```
However, I don't think we need to fix this, since we plan on moving away from this library in the coming days in favor of the new XboxController in WPILib.
