### ISSUE TITLE
create byte buffer from byte array instead of copying one at a time

### ISSUE THREAD

**Issue by leijurv** [RoboticsTeam4904/standard#140]
```
ByteBuffer canData = ByteBuffer.allocateDirect(8);
		for (int i = 0; i < 8; i++) {
			canData.put(i, data[i]);
		}
```
I believe you can create a byte buffer directly from a byte array instead of copying it in one byte at a time. 
In `org.usfirst.frc4904.standard.custom.CustomCAN`

**Comment by carturn** [comment]
Fixed in #128.
