### ISSUE TITLE
Double.MIN_VALUE

### ISSUE THREAD

**Issue by leijurv** [RoboticsTeam4904/standard#209]
/**
	 * A function for determining if floating point numbers are effectively zero.
	 * Floating point arithmetic tends to introduce very small errors.
	 *
	 * @param var
	 *        The floating point number you want to compare
	 * @return
	 * 		Whether or not it is within Double.MIN_VALUE of zero
	 */
	public static boolean isZero(double var) {
		return Math.abs(var) < Double.MIN_VALUE;
	}

The stated purpose is to check if something is close to zero.

However, `x < Double.MIN_VALUE` is ONLY true when `x` is exactly equal to zero.

**Comment by HowardStark** [comment]
Please fix and submit a pull request.
