### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ericsims** [RoboticsTeam4904/standard#230]
Hi! I want to use this code for a time of flight sensor board I am working on. That way FRC teams can use tof sensors right off the CAN Bus. Anyways, your code has no license currently, and I am hoping you can put one there. Maybe you guys should pick a license like MIT or BSD or unLicense so that others can use it?

**Comment by NikhilSuresh24** [comment]
@ericsims We have added a BSD license to our code. Good luck with your project!

**Comment by ericsims** [comment]
Oh awesome! Thanks! and good luck to your team this year!
