### ISSUE TITLE
getRate

### ISSUE THREAD

**Issue by carturn** [RoboticsTeam4904/standard#53]
Maybe getRate should be called getYawRate()? #51 
But the robot probably is not doing a barrel role.

**Comment by c0d3rman** [comment]
I will implement this change and also add `getPitchRate()` and `getRollRate()`. These will be helpful for things like detecting hitting an obstacle (`if (getPitchRate() > SOME_CONSTANT) {}`). I am considering adding the rates in a `RateIMU` subinterface. @carturn thoughts?

**Comment by carturn** [comment]
I do not think we should actually do this.

**Comment by c0d3rman** [comment]
Fair enough.
